/**
 * Differ Tests
 *
 * Tests for comparing existing copilot-instructions.md content with newly
 * composed content. Covers identical content, changed content, header
 * comment stripping, missing files, and human-readable summaries.
 */
import { describe, it, expect } from 'vitest';
import { diffInstructions } from '../differ';
import type { DiffResult } from '../differ';

// ─── Sample Content ─────────────────────────────────────────────────────────

const HEADER_COMMENT = `<!-- DO NOT EDIT THIS FILE MANUALLY -->
<!-- Generated by Copilot Compose from thomasiverson/copilot-instructions@main -->
<!-- Modules: coding-standards, security-checklist -->
<!-- Generated at: 2026-03-19T10:00:00.000Z -->
<!-- To update, run "Copilot Compose: Sync Instructions" or edit .github/copilot-compose.yaml -->`;

const BODY_CONTENT = `# Coding Standards

Use camelCase for variables and functions.

---

# Security Checklist

Never store secrets in source code.`;

const FULL_COMPOSED = `${HEADER_COMMENT}\n\n${BODY_CONTENT}`;

// Same body but different timestamp in header
const FULL_COMPOSED_DIFFERENT_TIMESTAMP = `<!-- DO NOT EDIT THIS FILE MANUALLY -->
<!-- Generated by Copilot Compose from thomasiverson/copilot-instructions@main -->
<!-- Modules: coding-standards, security-checklist -->
<!-- Generated at: 2026-03-19T14:30:00.000Z -->
<!-- To update, run "Copilot Compose: Sync Instructions" or edit .github/copilot-compose.yaml -->

${BODY_CONTENT}`;

const MODIFIED_BODY = `# Coding Standards

Use camelCase for variables and functions.
Use PascalCase for classes.

---

# Security Checklist

Never store secrets in source code.
Use environment variables for configuration.`;

const FULL_COMPOSED_MODIFIED = `${HEADER_COMMENT}\n\n${MODIFIED_BODY}`;

// ─── Test Suites ────────────────────────────────────────────────────────────

describe('Differ', () => {
  describe('identical content', () => {
    it('should detect identical content (no diff)', () => {
      const result = diffInstructions(FULL_COMPOSED, FULL_COMPOSED);

      expect(result.isDifferent).toBe(false);
      expect(result.summary).toBeTruthy();
    });

    it('should ignore header comment timestamp differences', () => {
      // The only difference is the timestamp in the header comment
      const result = diffInstructions(FULL_COMPOSED, FULL_COMPOSED_DIFFERENT_TIMESTAMP);

      expect(result.isDifferent).toBe(false);
    });
  });

  describe('content changes', () => {
    it('should detect content changes', () => {
      const result = diffInstructions(FULL_COMPOSED, FULL_COMPOSED_MODIFIED);

      expect(result.isDifferent).toBe(true);
      expect(result.summary).toBeTruthy();
    });

    it('should provide human-readable diff summary', () => {
      const result = diffInstructions(FULL_COMPOSED, FULL_COMPOSED_MODIFIED);

      // Summary should mention lines added/removed or similar change indication
      expect(result.summary.length).toBeGreaterThan(0);
      // Summary should contain some indicator of what changed
      expect(
        result.summary.includes('added') ||
          result.summary.includes('removed') ||
          result.summary.includes('changed') ||
          result.summary.includes('+') ||
          result.summary.includes('-') ||
          result.summary.includes('line'),
      ).toBe(true);
    });

    it('should include existing and composed content in result', () => {
      const result = diffInstructions(FULL_COMPOSED, FULL_COMPOSED_MODIFIED);

      expect(result.existing).toBe(FULL_COMPOSED);
      expect(result.composed).toBe(FULL_COMPOSED_MODIFIED);
    });
  });

  describe('missing existing file', () => {
    it('should handle null existing file (treat as all-new)', () => {
      const result = diffInstructions(null, FULL_COMPOSED);

      expect(result.isDifferent).toBe(true);
      expect(result.existing).toBe('');
      expect(result.composed).toBe(FULL_COMPOSED);
    });

    it('should provide summary for new file creation', () => {
      const result = diffInstructions(null, FULL_COMPOSED);

      expect(result.summary).toBeTruthy();
      // Summary should indicate it's a new file
      expect(
        result.summary.toLowerCase().includes('create') ||
          result.summary.toLowerCase().includes('new') ||
          result.summary.includes('No existing'),
      ).toBe(true);
    });
  });

  describe('edge cases', () => {
    it('should handle empty string existing file', () => {
      const result = diffInstructions('', FULL_COMPOSED);

      expect(result.isDifferent).toBe(true);
    });

    it('should handle empty composed content against existing content', () => {
      const result = diffInstructions(FULL_COMPOSED, '');

      expect(result.isDifferent).toBe(true);
    });

    it('should handle both empty', () => {
      const result = diffInstructions('', '');

      expect(result.isDifferent).toBe(false);
    });

    it('should handle body-only comparison (no header in either)', () => {
      const result = diffInstructions(BODY_CONTENT, BODY_CONTENT);

      expect(result.isDifferent).toBe(false);
    });

    it('should detect changes when only body differs (both have headers)', () => {
      const existingWithHeader = `${HEADER_COMMENT}\n\n${BODY_CONTENT}`;
      const composedWithHeader = `${HEADER_COMMENT}\n\n${MODIFIED_BODY}`;
      const result = diffInstructions(existingWithHeader, composedWithHeader);

      expect(result.isDifferent).toBe(true);
    });
  });
});
