import type { ComposeConfig, ComposeModule, ComposeResult } from './types';
import { ComposeError } from './types';

/**
 * Build the auto-generated header comment with provenance info.
 */
function buildHeader(config: ComposeConfig, moduleIds: string[], timestamp: string): string {
  const lines = [
    '<!-- DO NOT EDIT THIS FILE MANUALLY -->',
    `<!-- Generated by Copilot Compose from ${config.source.repo}@${config.source.ref} -->`,
    `<!-- Modules: ${moduleIds.join(', ')} -->`,
    `<!-- Generated at: ${timestamp} -->`,
    `<!-- To update, run "Copilot Compose: Sync Instructions" or edit .github/copilot-compose.yaml -->`,
    '',
  ];
  return lines.join('\n');
}

/**
 * Apply overrides (prepend/append) to module content.
 */
function applyOverrides(
  moduleId: string,
  content: string,
  overrides?: ComposeConfig['overrides']
): string {
  if (!overrides || !overrides[moduleId]) {
    return content;
  }

  const override = overrides[moduleId];
  const parts: string[] = [];

  if (override.prepend) {
    parts.push(override.prepend);
  }
  parts.push(content);
  if (override.append) {
    parts.push(override.append);
  }

  return parts.join('\n\n');
}

/**
 * Compose modules into the final copilot-instructions.md content.
 */
export function compose(
  modules: Map<string, ComposeModule>,
  config: ComposeConfig
): ComposeResult {
  const timestamp = new Date().toISOString();
  const repoWideModules: ComposeModule[] = [];
  const pathSpecificModules: Array<{ module: ComposeModule; applyTo: string }> = [];

  // Separate repo-wide from path-specific modules
  for (const moduleId of config.modules) {
    const mod = modules.get(moduleId);
    if (!mod) {
      throw new ComposeError(`Module '${moduleId}' not found in fetched modules`, 'COMPOSE_ERROR');
    }

    if (mod.frontmatter.scope === 'path-specific' && mod.frontmatter.applyTo) {
      pathSpecificModules.push({ module: mod, applyTo: mod.frontmatter.applyTo });
    } else {
      repoWideModules.push(mod);
    }
  }

  // Handle path-specific modules from config.pathInstructions
  if (config.pathInstructions) {
    for (const pi of config.pathInstructions) {
      const mod = modules.get(pi.id);
      if (mod) {
        pathSpecificModules.push({ module: mod, applyTo: pi.applyTo });
      }
    }
  }

  // Build the main file content
  const mainSections: string[] = [];

  if (config.sync.header) {
    mainSections.push(buildHeader(config, config.modules, timestamp));
  }

  for (let i = 0; i < repoWideModules.length; i++) {
    const mod = repoWideModules[i];
    const content = applyOverrides(mod.frontmatter.id, mod.content, config.overrides);
    mainSections.push(content);

    if (i < repoWideModules.length - 1) {
      mainSections.push(config.sync.separator);
    }
  }

  const mainFile = mainSections.join('\n\n') + '\n';

  // Build path-specific files
  const pathFiles = pathSpecificModules.map(({ module: mod, applyTo }) => {
    const content = applyOverrides(mod.frontmatter.id, mod.content, config.overrides);
    const fileContent = config.sync.header
      ? buildHeader(config, [mod.frontmatter.id], timestamp) + '\n' + content + '\n'
      : content + '\n';
    return { path: applyTo, content: fileContent };
  });

  return {
    mainFile,
    pathFiles,
    metadata: {
      source: `${config.source.repo}@${config.source.ref}`,
      modules: config.modules,
      generatedAt: timestamp,
    },
  };
}
